In [2]:
prices_a = [8.70, 8.91, 8.71]

In [3]:
prices_a[1:]

[8.91, 8.71]

In [4]:
prices_a[:-1]

[8.7, 8.91]

In [5]:
import numpy as np

In [6]:
np_prices = np.array(prices_a)

In [7]:
np_prices

array([8.7 , 8.91, 8.71])

In [8]:
np.array(np_prices[1:])

array([8.91, 8.71])

In [11]:
np.array(np_prices[1:])/np.array(np_prices[:-1]) - 1

array([ 0.02413793, -0.02244669])

In [12]:
import pandas as pd

In [13]:
pd_prices = pd.DataFrame({
    "BLUE": [8.70, 8.91, 8.71, 8.43, 8.73],
    "ORANGE": [10.66, 11.08, 10.71, 11.59, 12.11]
})

In [14]:
pd_prices

BLUE  ORANGE
0  8.70   10.66
1  8.91   11.08
2  8.71   10.71
3  8.43   11.59
4  8.73   12.11

In [16]:
pd_prices.iloc[1:]

BLUE  ORANGE
1  8.91   11.08
2  8.71   10.71
3  8.43   11.59
4  8.73   12.11

In [17]:
pd_prices.iloc[:-1]

BLUE  ORANGE
0  8.70   10.66
1  8.91   11.08
2  8.71   10.71
3  8.43   11.59

# same rows are aligned and divided 

In [18]:
pd_prices.iloc[1:]/pd_prices.iloc[:-1]

BLUE  ORANGE
0   NaN     NaN
1   1.0     1.0
2   1.0     1.0
3   1.0     1.0
4   NaN     NaN

## using the index this rows are getting aligned.

In [20]:
pd_prices.iloc[1:].values/pd_prices.iloc[:-1] - 1

BLUE    ORANGE
0  0.024138  0.039400
1 -0.022447 -0.033394
2 -0.032147  0.082166
3  0.035587  0.044866

## with values, it returns numpy maatrix without index

In [21]:
pd_prices.shift(1)

BLUE  ORANGE
0   NaN     NaN
1  8.70   10.66
2  8.91   11.08
3  8.71   10.71
4  8.43   11.59

In [23]:
pd_prices/pd_prices.shift(1) - 1

BLUE    ORANGE
0       NaN       NaN
1  0.024138  0.039400
2 -0.022447 -0.033394
3 -0.032147  0.082166
4  0.035587  0.044866

In [24]:
pd_prices.shift(-1)/pd_prices - 1

BLUE    ORANGE
0  0.024138  0.039400
1 -0.022447 -0.033394
2 -0.032147  0.082166
3  0.035587  0.044866
4       NaN       NaN

In [25]:
pd_prices

BLUE  ORANGE
0  8.70   10.66
1  8.91   11.08
2  8.71   10.71
3  8.43   11.59
4  8.73   12.11

In [26]:
pd_prices.pct_change()

BLUE    ORANGE
0       NaN       NaN
1  0.024138  0.039400
2 -0.022447 -0.033394
3 -0.032147  0.082166
4  0.035587  0.044866

In [27]:
returns = pd_prices.pct_change()

In [28]:
returns

BLUE    ORANGE
0       NaN       NaN
1  0.024138  0.039400
2 -0.022447 -0.033394
3 -0.032147  0.082166
4  0.035587  0.044866

In [33]:
np.prod(returns + 1) - 1

BLUE      0.003448
ORANGE    0.136023
dtype: float64

In [32]:
((returns + 1).prod() - 1)*100

BLUE       0.344828
ORANGE    13.602251
dtype: float64

In [35]:
(returns + 1).mean()

BLUE      1.001283
ORANGE    1.033260
dtype: float64

In [36]:
(returns + 1).std()

BLUE      0.033565
ORANGE    0.048328
dtype: float64